language: ruby
rvm:
  - 2.6.3

sudo: false

services:
  - docker

addons:
  ssh_known_hosts: codehearts.com

cache:
  directories:
    - $HOME/.rvm/gems/
install:
  - gem install html-proofer

script:
  - docker-compose pull --parallel
  - JEKYLL_CMD=build docker-compose up --exit-code-from jekyll
  - htmlproofer --check_html --check_img_http --check_favicon --url_ignore /cif.rochester.edu/ _site/

before_deploy:
  - umask 0377
  - openssl aes-256-cbc -K $encrypted_9b3e92350451_key -iv $encrypted_9b3e92350451_iv
    -in .deploy.key.enc -out .deploy.key -d
  - umask 0022

deploy:
  skip_cleanup: true
  provider: script
  script: rsync -azP -e 'ssh -i .deploy.key' --delete
          _site/ deploy@codehearts.com:/var/www/codehearts.com/html/
  on:
    branch: master
