language: node_js
node_js:
  - 12

services:
  - docker

env:
  - HINT_TRACKING=off

addons:
  ssh_known_hosts: codehearts.com
  apt:
    packages:
      - brotli
      - zopfli

before_script:
  - docker-compose pull --parallel
  - JEKYLL_CMD=build docker-compose up --exit-code-from jekyll
  - docker-compose up -d
  - sleep 10

before_deploy:
  - umask 0377
  - openssl aes-256-cbc -K $encrypted_9b3e92350451_key -iv $encrypted_9b3e92350451_iv
    -in .deploy.key.enc -out .deploy.key -d
  - umask 0022

deploy:
  skip_cleanup: true
  provider: script
  script: find _site/ -regex '.*\.\(html\|css\|js\|svg\|webmanifest\)' \
            -exec sh -c 'zopfli $@; brotli $@' _ {} +
          rsync -azP -e 'ssh -i .deploy.key' --delete _site/ \
            deploy@codehearts.com:/var/www/codehearts.com/html/
  on:
    branch: master
