version: '3.3'

services:
  # Jekyll service for generating the static site
  jekyll:
    image: 'jekyll/jekyll:4.2.0'
    # JEKYLL_CMD can be set to change the run behavior (defaults to "build --watch")
    command: jekyll ${JEKYLL_CMD-build --watch}
    networks:
      - jekyll_gotenberg
    volumes:
      - ./:/srv/jekyll
  # Nginx serves the static site on port 80, for Gotenberg and local developers
  nginx:
    image: 'nginx:1.20.0'
    networks:
      - jekyll_gotenberg
    ports:
      - '80:80'
    volumes:
      - ./_site:/usr/share/nginx/html
  # Gotenberg receives requests on port 3000
  gotenberg:
    image: 'thecodingmachine/gotenberg:6.4.3'
    environment:
      # Disable Open Office conversion
      DISABLE_UNOCONV: 1
    networks:
      - jekyll_gotenberg
    expose:
      - '3000'

networks:
  jekyll_gotenberg:
    driver: 'bridge'
