name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get -q update && sudo apt-get install -y --no-install-recommends brotli zopfli
    - name: Build
      run: |
        mkdir .jekyll-cache _site
        docker-compose up --exit-code-from jekyll
        docker-compose up -d nginx
        docker-compose exec -T nginx chown -R $UID /usr/share/nginx/html/
      env:
        JEKYLL_CMD: build
    - name: Configure SSH
      run: |
        mkdir ~/.ssh
        echo 'codehearts.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDFZbgWZp5pnK4NwVxYB10GZw13wrTPwQ39Q7S3VTUyukXTATLfw9dHK5tumRTVnuxxIvDKuWFFzXuStD20Iq6c=' > ~/.ssh/known_hosts
        umask 0377
        echo "$DEPLOY_KEY" > deploy.key
        umask 0022
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    - name: Compress resources
      run: >
        find _site/ \( -name '*.html' -o -name '*.css' -o -name '*.js' -o -name '*.svg' -o -name '*.webmanifest' \) -exec zopfli {} + -exec brotli {} +
    - name: Deploy
      run: rsync -azP -e 'ssh -i deploy.key' --delete _site/ deploy@codehearts.com:/var/www/codehearts.com/html/
    - name: Post-deploy check
      run: npx hint https://codehearts.com
      env:
        HINT_TRACKING: off
